services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

MSYS_NO_PATHCONV=1 winpty docker run -it \
-e POSTGRES_USER="root" \
-e POSTGRES_PASSWORD="root" \
-e POSTGRES_DB="ny_taxi" \
-v //c/Users/Skylake/documents/github/data_engineering_zoomcamp/2_docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data \
-p 5432:5432 \
postgres:17

sudo chmod -R 777 ny_taxi_postgres_data/


winpty docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  dpage/pgadmin4


 #network
 docker network create pg-network

winpty docker run -it \
-e POSTGRES_USER="root" \
-e POSTGRES_PASSWORD="root" \
-e POSTGRES_DB="ny_taxi" \
-v //c/Users/Skylake/documents/github/data_engineering_zoomcamp/2_docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data \
-p 5432:5432 \
--network=pg-network \
--name pg-database \
postgres:13

winpty docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  --network=pg-network \
  --name pgadmin \
  dpage/pgadmin4

url="wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz"
wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
python pl_ingest_data.py /
  --user=postgres /
  --password=postgres /
  --host=pgdatabase /
  --port=5432 /
  --db=nyc_taxi
  --table_name=pl_yellow_taxi /
  --url=${url}

 #lets do it in on line, something is off with line continuation
 python ingest_data.py --user=postgres --password=postgres --host=localhost --port=5432 --db=nyc_taxi --table_name=pl_yellow_taxi --url=${url}

 python ingest_data.py --user=pgadmin@pgadmin.com --password=pgadmin --host=pgdatabase --port=5432 --db=nyc_taxi --table_name=pl_yellow_taxi --url=${url}

 
 winpty docker run taxi_ingest:v001 --user=postgres --password=postgres --host=pgdatabase --port=5432 --db=nyc_taxi --table_name=pl_yellow_taxi --url=${url}

winpty docker run -it --network=pg-network taxi_ingest:v001 --user=postgres --password=postgres --host=pgdatabase --port=5432 --db=nyc_taxi --table_name=pl_yellow_taxi --url=${url}